apiVersion: apps/v1
kind: Deployment
metadata:
  name: reno-frontend
  namespace: reno
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reno-frontend
  template:
    metadata:
      labels:
        app: reno-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/anandzambad/reno-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: /api
---
apiVersion: v1
kind: Service
metadata:
  name: reno-frontend
  namespace: reno
spec:
  selector:
    app: reno-frontend
  ports:
    - port: 3000
      targetPort: 3000
