apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reno-backend
  namespace: reno
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reno-backend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reno-frontend
  namespace: reno
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reno-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
