apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reno
  namespace: reno
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  rules:
    - host: reno.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: reno-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reno-frontend
                port:
                  number: 3000
