apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reno-prod
resources:
  - ../../base
  - namespace.yaml
namePrefix: prod-
patches:
  - path: patch-host.yaml
  - path: patch-replicas.yaml
images:
  - name: ghcr.io/anandzambad/reno-frontend
    newName: ghcr.io/anandzambad/reno-frontend
    newTag: prod
  - name: ghcr.io/anandzambad/reno-backend
    newName: ghcr.io/anandzambad/reno-backend
    newTag: prod
