apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reno-beta
resources:
  - ../../base
  - namespace.yaml
namePrefix: beta-
patches:
  - path: patch-host.yaml
images:
  - name: ghcr.io/anandzambad/reno-frontend
    newName: ghcr.io/anandzambad/reno-frontend
    newTag: beta
  - name: ghcr.io/anandzambad/reno-backend
    newName: ghcr.io/anandzambad/reno-backend
    newTag: beta
